FROM node:slim as builder

WORKDIR /opt/app
COPY ./package.json .
RUN yarn install
COPY . .
RUN yarn build

FROM nginx
RUN sed  -i 's/80;/3000;/g' /etc/nginx/conf.d/default.conf
COPY --from=builder /opt/app/build /usr/share/nginx/html
