version: '3.7'

services:
  redis:
    image: redis
  postgres:
    image: postgres
    hostname: ${PGHOST}
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - ${PGPORT}:${PGPORT}
  backend:
    image: backend
    hostname: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      PGPORT: ${PGPORT}
      PGUSER: ${PGUSER}
      PGHOST: ${PGHOST}
      PGDATABASE: ${PGDATABASE}
      PGPASSWORD: ${PGPASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - /opt/app/node_modules
      - ./backend:/opt/app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
  frontend:
    image: frontend
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /opt/app/node_modules
      - ./frontend:/opt/app
    tty: true
  nginx:
    image: nginx-app
    hostname: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
