version: '3.7'

services:
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: labDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      PGPORT: 5432
      PGHOST: postgres
      PGDATABASE: labDb
      PGUSER: postgres
      PGPASSWORD: postgres
    ports:
      - "90:8080"
    depends_on:
      - postgres
      - redis
