apiVersion: v1

kind: Service

metadata:
  name: myapp-service
  namespace: cube
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30005
  selector:
    app: myapp
    type: backend
