apiVersion: apps/v1

kind: ReplicaSet

metadata:
    name: my-rs
    labels:
        app: my-app
spec:
  template:
    metadata:
      name: my-app_pod
      labels:
        app: my-app
    spec:
        containers:
            - name: backend
              image: backend

  replicas: 3
  selector:
    matchLabels:
      app: my-app
